### ISSUE TITLE
no grafana dashboards are available

### ISSUE THREAD

**Issue by goern** [operate-first/support#218] opened 2021-04-28 09:22 UTC
**Describe the bug**
It seems that we have lost all the Thoth (or all-all) dashboards.

**To Reproduce**
1. Go to https://grafana-route-opf-monitoring.apps.zero.massopen.cloud/
2. See error: no dashboards

**Expected behaviour**
We can see dashboards.

/kind bug
/priority critical-urgent
/sig devops

**Comment by tumido** [comment] 2021-04-28 09:49
@4n4nd may this be related to the https://github.com/operate-first/apps/pull/576 ?

The dashboards are present in the cluster, but not available in Grafana:
![image](https://user-images.githubusercontent.com/7453394/116384024-bdfb2880-a817-11eb-944e-3514db615261.png)

![image](https://user-images.githubusercontent.com/7453394/116384050-c5223680-a817-11eb-9ca2-a9ffe0ee185c.png)

**Comment by tumido** [comment] 2021-04-28 09:51
Probably related:
```
oc get grafanas -n opf-monitoring
NAME          AGE
grafana       49d
odh-grafana   7d17h
```

**Comment by tumido** [comment] 2021-04-28 10:04
@4n4nd so.. I've found the root cause. Do you know how to bypass the proxy we've added at https://github.com/operate-first/apps/pull/573

The operator is complaining:
```
{"level":"error","ts":1619586556.1305199,"logger":"controller_grafanadashboard","msg":"failed to get or create namespace folder Thoth-Station for dashboard ","error":"error creating folder, expected status 200 but got 403","stacktrace":"github.com/go-logr/zapr.(*zapLogger).Error\n\t/home/hstefans/go/pkg/mod/github.com/go-logr/zapr@v0.1.1/zapr.go:128\ngithub.com/integr8ly/grafana-operator/v3/pkg/controller/grafanadashboard.(*ReconcileGrafanaDashboard).reconcileDashboards\n\tgrafana-operator/pkg/controller/grafanadashboard/dashboard_controller.go:253\ngithub.com/integr8ly/grafana-operator/v3/pkg/controller/grafanadashboard.(*ReconcileGrafanaDashboard).Reconcile\n\tgrafana-operator/pkg/controller/grafanadashboard/dashboard_controller.go:136\ngithub.com/integr8ly/grafana-operator/v3/pkg/controller/grafanadashboard.add.func1\n\tgrafana-operator/pkg/controller/grafanadashboard/dashboard_controller.go:86\ngithub.com/integr8ly/grafana-operator/v3/pkg/controller/grafanadashboard.add.func2\n\tgrafana-operator/pkg/controller/grafanadashboard/dashboard_controller.go:92"}
```

**Comment by 4n4nd** [comment] 2021-04-28 13:45
> Probably related:
> 
> ```
> oc get grafanas -n opf-monitoring
> NAME          AGE
> grafana       49d
> odh-grafana   7d17h
> ```
> 
> I've deleted `odh-grafana` since it's failing anyways. Duplicit Grafanas were probably introduced before [operate-first/apps#576](https://github.com/operate-first/apps/pull/576) (this PR partially fixed it, but not fully)

@tumido looks like we are not overriding the upstream grafana but creating a new one ([upstream](https://github.com/opendatahub-io/odh-manifests/blob/master/grafana/grafana/base/grafana.yaml#L4))

**Comment by tumido** [comment] 2021-04-28 13:57
@4n4nd I think we did, but we don't now - this got fixed by https://github.com/operate-first/apps/pull/576 (but the duplicit resource wasn't removed).

What matters for ODH is the filename - not resource name, we should be fine there. Once ODH reconciles, we should be still left with a single grafana there.

**Comment by tumido** [comment] 2021-04-28 13:57
Currently the only issue remaining to solve is https://github.com/operate-first/support/issues/218#issuecomment-828329797

**Comment by 4n4nd** [comment] 2021-04-28 13:59
> Currently the only issue remaining to solve is [#218 (comment)](https://github.com/operate-first/support/issues/218#issuecomment-828329797)

I found that the operator for reason is using the route to communicate with the deployment. The current solution I have found is to disable the route creatiion by the grafana-operator and create a route manually

**Closed** 2021-04-28 14:46 UTC
Labels: human_intervention_required, kind/bug, priority/critical-urgent, sig/devops

**Comment by goern** [comment] 2021-04-28 14:53
@pacospace please check if our data is visible again, thx

**Comment by pacospace** [comment] 2021-04-28 15:03
> @pacospace please check if our data is visible again, thx

Yes they seem back :)
