### ISSUE TITLE
Can Members of the data science group get access to the Jupyterhub project so that we can view our own pod logs?

### ISSUE THREAD

**Issue by MichaelClifford** [operate-first/support#156] opened 2021-03-25 19:50 UTC
### Requested actions

Select all that apply:

- [ ] Create a new ArgoCD project for existing team
- [ ] Enlist an application to be deployed automatically via ArgoCD
- [x] Add a new user to an ArgoCD Project

#### Creating a new project

1. **Team name**:
   Please tell us your team name, which corresponds to [an already available user `Group`](https://github.com/operate-first/apps/tree/master/cluster-scope/base/groups).

2. **Target cluster**:
   Choose an environment from [this list](https://github.com/operate-first/apps/tree/master/cluster-scope/overlays)

3. **Managed namespaces**:
   The target namespaces that should be managed by ArgoCD. Preferably using [a single (team name) prefix](https://github.com/operate-first/support/blob/main/docs/onboarding_to_argocd.md#additional-notes).

#### Deploying a new application:

1. **Team name or your Argo CD project**:
   Please specify your Argo CD project name. If you're using this template to request both, project and application, you can skip this field.

2. **Application source git repository**:
   URL to the source repository. Please specify if the repository is private. In that case we'll exchange credentials later on.

3. **Path to manifests within the repository**:
   Relative path within the repository to the resources you want Argo CD to deploy.

4. **Target cluster**:
   Choose an environment from [this list](https://github.com/operate-first/apps/tree/master/cluster-scope/overlays)

5. **Target namespace for the application**:
   Please specify an existing namespace in the target cluster which is owned by your team. If you want a new namespace to be created, please file an issue via the [Onboarding to a cluster](https://github.com/operate-first/support/issues/new/choose) template.

#### Add a new user to an ArgoCD Project:

Please note that we use OCP Groups to grant access to ArgoCD projects, this means that this user will be added to your team's OCP group on MOC, and thus have the same permissions as all other members of this group. As such we require an existing member of this group to vouch for you.

1. **User name**
   Please specify your MOC OCP User Name. E.g. (john at gmail.com)

mcliffor

2. **Team name**
   Please specify your team Name.

data science

3. **ArgoCD Project**
   Please specify the ArgoCD project this user should be added to.

jupyterhub ( ?) 

---

If you don't want to wait for the maintainers to notice this issue, you can do the changes yourself. Please follow the [docs/onboarding_team_to_argo_cd.md](https://github.com/operate-first/support/blob/main/docs/onboarding_to_argocd.md) and/or the [docs/add_application.md](https://github.com/operate-first/argocd-apps/blob/main/docs/add_application.md) guides.

**Comment by tumido** [comment] 2021-03-26 09:51
@MichaelClifford just to get this clarified, what do you want exactly? You want to be able to log in to:
https://console-openshift-console.apps.zero.massopen.cloud/

go to `opf-jupyterhub` project and see your pods, right?

**Comment by tumido** [comment] 2021-03-26 09:58
/kind bug

This should have been resolved by https://github.com/operate-first/apps/issues/428 it was not, sorry for that

**Comment by tumido** [comment] 2021-03-26 12:20
So, the role works as intended, though you can't access the project :facepalm: Investigating

This should work on your account though:
```
oc get pods -n opf-jupyterhub
```

**Comment by MichaelClifford** [comment] 2021-03-26 12:28
Thank @tumido ! I can confirm 

`oc get pods -n opf-jupyterhub` shows the pods running there and  `oc logs <pod_name> -n opf-jupyterhub` displays the logs.

**Closed** 2021-03-29 13:44 UTC
Labels: human_intervention_required, kind/bug, onboarding

**Comment by tumido** [comment] 2021-03-29 13:54
@MichaelClifford resolved. `opf-jupyterhub` is now listed on the OCP web console. :+1: 

![image](https://user-images.githubusercontent.com/7453394/112847109-069fb480-90a7-11eb-9316-88ee055de764.png)
