### ISSUE TITLE
Black Flake ArgoCD app is failing to sync

### ISSUE THREAD

**Issue by 4n4nd** [operate-first/support#122] opened 2021-03-15 18:40 UTC
**Describe the bug**
App fails to sync and project manifests are not applied.
ArgoCD app link: https://argocd-server-argocd.apps.moc-infra.massopen.cloud/applications/black-flake?conditions=false

**Expected behaviour**
syncs successfully and applies the manifests in the projects

**Screenshots**
Following Sync Error can be seen:
![Screenshot from 2021-03-15 14-38-48](https://user-images.githubusercontent.com/22333506/111204128-337aa480-859c-11eb-8530-7740fb9d5e0f.png)

**Comment by tumido** [comment] 2021-03-16 11:57
The problem is in the application manifests. Issue raised back to the application team.

**Comment by tumido** [comment] 2021-03-16 12:08
I admit the error is not straightforward to decipher. /shrug

Solution found here:
https://github.com/argoproj/argo-helm/issues/507#issuecomment-785202803

Closing as invalid

**Closed by tumido** 2021-03-16 12:08 UTC
Labels: invalid
