### ISSUE TITLE
Unable to access public pgbouncer endpoint from jupyter notebook

### ISSUE THREAD

**Issue by jasonbrooks** [operate-first/support#309] opened 2021-07-14 17:22 UTC
I'm attempting to access a postgresql database that's running behind a pgbouncer proxy on a public IP from within a jupyter notebook running in the Operate First cloud. I'm able to access the database from my notebook, from a pod in another openshift cluster, and from jupyter notebooks running locally and on that openshift cluster.

**To Reproduce**
1. Go to https://odh.operate-first.cloud/
2. Click on launch jupyterhub
3. Launch a terminal and `pip install psycopg2`
4. Launch a notebook and test with code like:

```
import psycopg2 

conn=psycopg2.connect('dbname=foo host=foo.bar port=6432 user=foo password=bar')
cur = conn.cursor()
cur.execute("""SELECT COUNT(*) FROM testdb""")
for rec in cur:
    print(rec[0])
```

5. See error:

```
OperationalError: could not connect to server: Connection timed out
	Is the server running on host foo.bar and accepting
	TCP/IP connections on port 6432?
```

**Expected behaviour**
Database is accessed

**Comment by jberkus** [comment] 2021-07-14 17:30
More information: we specifically checked pgbouncer and firewall logs on the database server, and no connection attempts got that far.  So the connection is definitely being blocked, or at least not routed, inside OF.

**Comment by 4n4nd** [comment] 2021-07-14 19:13
similar issue: https://github.com/operate-first/support/issues/173

**Comment by HumairAK** [comment] 2021-07-14 19:18
@larsks any ideas on why they are experiencing the following behavior? 

> Josh Berkus wrote:
so I can resolve the server's address, but it seems like all outgoing connections to it are blocked. Which is, btw, the Openshift default.

> Josh Berkus wrote:
[1000950000@jupyterhub-nb-jberkus-40redhat-2ecom ~]$ ssh mailto:jberkus@augur.osci.io|jberkus@augur.osci.io

> ssh: connect to host http://augur.osci.io|augur.osci.io port 22: Connection timed out

**Comment by larsks** [comment] 2021-07-21 13:26
I'm going to raise this issue with Boston University's IT department, because it sounds very similar to an issue [we encountered previously](https://github.com/CCI-MOC/ops-issues/issues/224). Note that issue took some time to resolve, although I hope things will move faster this time.

**Comment by larsks** [comment] 2021-07-21 18:46
Just to remind myself to I don't need to bother @naved001 next  time I need a host on a BU network other than 192.12.185.0/24:

```
14:31:16   larsks | @naved001  I know I've asked this question before, but I have forgotten the answer: machine I can log into which is on a BU   
                  | network other than 192.12.185.0/24?                                                                                           
14:34:15 naved001 | px2.massopen.cloud                                                                                                       
14:34:48 naved001 | @larsks ^^ that machine is the campus BU network (PRB lab specifically)                                                       
14:34:55   larsks | Thanks!                                                                                                                       
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - 
14:34:55 naved001 | there's also px1 and px3.                                                                                                     
```

**Comment by larsks** [comment] 2021-07-21 18:51
I've opened BU IS&T ticket INC13263917 for this issue.

**Comment by larsks** [comment] 2021-07-27 14:23
BU ticket INC13263917 has been picked up by a network engineer.

**Comment by cdolfi** [comment] 2021-07-27 18:19
For context:  augur.osci.io is one of the endpoints that is not accessible

**Comment by larsks** [comment] 2021-07-28 21:18
The initial response from network engineering is:

> It is confirmed that this is an asymmetric routing issue and the return traffic is coming back through CRC edge firewall which is stopping the traffic that originates from MGHPCC. I'm still investigating the cause and have confirmed with the NoX that the only advertisement they see from us for the 192.12.185.0/24 block is from the peer at the MGHPCC.
>
> I'll keep you updated.

**Comment by larsks** [comment] 2021-08-03 18:26
BU IT says that the problem is resolved:

> We believe we have this figured out and had to enlist the help of other ISPs in the path between us and Red Hat. Based on what I'm seeing after an ISP in between made a correction, any traffic to Red Hat will be through the main campus edge and not through the NoX at the MGHPCC as Red Hat only peers with the commodity Internet (Centurylink and Flexential).

My quick test suggests that this is true; I was able to access `augur.osci.io` port `22` from one of the openshift nodes. @cdolfi @jasonbrooks can you confirm that things are working?

**Comment by cdolfi** [comment] 2021-08-04 14:11
@larsks once the zero cluster for the operate first cloud environment is back up I will test it out!

**Comment by larsks** [comment] 2021-08-05 21:39
I'm closing this issue for now because I believe it's resolved. If you have the chance to test it out and find otherwise, please reopen it and ping me. Thanks!

**Closed by larsks** 2021-08-05 21:39 UTC
